services:

  exchange-service:
    image: exchange-service:latest
    build: ./exchange-service
    ports:
      - "8000:8000"
    restart: always
    networks:
      - anderson-network
    environment:
      TZ: "America/Sao_Paulo"
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-service:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/exchange_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123

  book-service:
    image: book-service:latest
    build: ./book-service
    ports:
      - "8100:8100"
    restart: always
    networks:
      - anderson-network
    environment:
      TZ: "America/Sao_Paulo"
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-service:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/book_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123

networks:
  anderson-network:
    driver: bridge